# Generated by Django 2.0 on 2018-02-07 13:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=1024, null=True)),
                ('content', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 2, 7, 13, 9, 30, 941104, tzinfo=utc))),
                ('update_time', models.DateTimeField(default=datetime.datetime(2018, 2, 7, 13, 9, 30, 941139, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='BinaryLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='common.ArticleType'),
        ),
    ]
