# Generated by Django 2.0 on 2018-02-26 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryLifeViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('is_anonymous', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('scheme', models.CharField(max_length=16)),
                ('remote_addr', models.GenericIPAddressField()),
                ('path', models.CharField(max_length=128)),
                ('cookies', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='BinaryLife',
        ),
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
        migrations.AddField(
            model_name='binarylifeviews',
            name='article',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='common.Article'),
        ),
    ]
