# Generated by Django 2.0.2 on 2018-11-08 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20181108_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articletype',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tagstype',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tagstype',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
