# Generated by Django 2.0.2 on 2018-11-09 01:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20181108_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('is_anonymous', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('scheme', models.CharField(max_length=16)),
                ('remote_addr', models.GenericIPAddressField()),
                ('path', models.CharField(max_length=128)),
                ('cookies', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='common.Article')),
            ],
        ),
        migrations.RemoveField(
            model_name='binarylifeviews',
            name='article',
        ),
        migrations.DeleteModel(
            name='BinaryLifeViews',
        ),
    ]
