# Generated by Django 2.0.2 on 2018-11-12 02:14

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('common', '0006_auto_20181112_0950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagsType',
            new_name='ArticleTags',
        ),
    ]
