# Generated by Django 2.0.2 on 2018-11-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20181112_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewsrecord',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='jedore', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='ip_view',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='page_view',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='unique_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
