# Generated by Django 2.0.2 on 2018-11-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20181112_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='comment',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
