# Generated by Django 2.0.2 on 2018-11-14 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20181113_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomments',
            options={'ordering': ('-create_time',)},
        ),
    ]
