# Generated by Django 2.0.2 on 2019-01-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20181114_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='non_technical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articletags',
            name='non_technical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articletype',
            name='non_technical',
            field=models.BooleanField(default=False),
        ),
    ]
